/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as ControlRouteImport } from './routes/control'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksSyncListo360RouteImport } from './routes/api/public/hooks/sync-listo360'
import { Route as ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRouteImport } from './routes/api/public/hooks/src/routes/api/public/hooks/sync-healthcon'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncListo360Route =
  ApiPublicHooksSyncListo360RouteImport.update({
    id: '/api/public/hooks/sync-listo360',
    path: '/api/public/hooks/sync-listo360',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRoute =
  ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRouteImport.update({
    id: '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon',
    path: '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/tv': typeof TvRoute
  '/api/public/hooks/sync-listo360': typeof ApiPublicHooksSyncListo360Route
  '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon': typeof ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/tv': typeof TvRoute
  '/api/public/hooks/sync-listo360': typeof ApiPublicHooksSyncListo360Route
  '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon': typeof ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/tv': typeof TvRoute
  '/api/public/hooks/sync-listo360': typeof ApiPublicHooksSyncListo360Route
  '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon': typeof ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control'
    | '/tv'
    | '/api/public/hooks/sync-listo360'
    | '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/control'
    | '/tv'
    | '/api/public/hooks/sync-listo360'
    | '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon'
  id:
    | '__root__'
    | '/'
    | '/control'
    | '/tv'
    | '/api/public/hooks/sync-listo360'
    | '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlRoute: typeof ControlRoute
  TvRoute: typeof TvRoute
  ApiPublicHooksSyncListo360Route: typeof ApiPublicHooksSyncListo360Route
  ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRoute: typeof ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-listo360': {
      id: '/api/public/hooks/sync-listo360'
      path: '/api/public/hooks/sync-listo360'
      fullPath: '/api/public/hooks/sync-listo360'
      preLoaderRoute: typeof ApiPublicHooksSyncListo360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon': {
      id: '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon'
      path: '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon'
      fullPath: '/api/public/hooks/src/routes/api/public/hooks/sync-healthcon'
      preLoaderRoute: typeof ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlRoute: ControlRoute,
  TvRoute: TvRoute,
  ApiPublicHooksSyncListo360Route: ApiPublicHooksSyncListo360Route,
  ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRoute:
    ApiPublicHooksSrcRoutesApiPublicHooksSyncHealthconRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
